@echo off
chcp 65001 > nul
attrib +h "2)———————————[ SRC 处理 —— Data_src Tools ]——————————————————————————————.bat"
attrib -h "2)++++++++++++++++[ SRC 处理 —— Data_src Tools ]+++++++++++++++++++++++++++++++++++++++++++.bat"
attrib -h "2.1)--- 切脸 data_src 手动 ------------------------- data_src faceset extract MANUAL.bat"
attrib -h "2.1)--- 切脸 data_src 自动 ------------------------- data_src faceset extract.bat"
attrib -h "2.2)--- SRC-aligned 预览 -------------------------- data_src view aligned result.bat"
attrib -h "2.3)--- SRC-aligned 检查错误 --------------------- data_src add landmarks debug images.bat"
attrib -h "2.3)--- SRC-aligned 缩放尺寸 --------------------- data_src util faceset resize.bat"
attrib -h "2.4)--- SRC-aligned 排序 -------------------------- data_src sort.bat"
attrib -h "2.5)--- SRC-aligned 打包 -------------------------- data_src util faceset pack.bat"
attrib -h "2.5)--- SRC-aligned 解包 -------------------------- data_src util faceset unpack.bat"
attrib -h "2.6)--- SRC-aligned 文件名恢复 ------------------- data_src util recover original filename.bat"
attrib -h "2.6)--- SRC-aligned 高清修复 --------------------- data_src util faceset enhance.bat"
attrib -h "2.7)--- SRC-aligned 数据保存 --------------------- data_src util faceset metadata save.bat"
attrib -h "2.7)--- SRC-aligned 数据恢复 --------------------- data_src util faceset metadata restore.bat"
