@echo off
chcp 65001 > nul
attrib +h "3)———————————[ DST 处理 —— Data_dst Tools ]——————————————————————————————.bat"
attrib -h "3)++++++++++++++++[ DST 处理 —— Data_dst Tools ]+++++++++++++++++++++++++++++++++++++++++++.bat"
attrib -h "3.1)--- 切脸 data_dst 半自动 ---------------------- data_dst faceset extract + manual fix.bat"
attrib -h "3.1)--- 切脸 data_dst 手动 ------------------------- data_dst faceset extract MANUAL.bat"
attrib -h "3.1)--- 切脸 data_dst 自动 ------------------------- data_dst faceset extract.bat"
attrib -h "3.1)--- 提取 aligned_debug 删掉的人脸 ---------- data_dst faceset MANUAL RE-EXTRACT DELETED ALIGNED_DEBUG.bat"
attrib -h "3.2)--- DST-aligned 预览 -------------------------- data_dst view aligned results.bat"
attrib -h "3.3)--- DST-aligned 检查错误 --------------------- data_dst add landmarks debug images.bat"
attrib -h "3.3)--- DST-aligned 缩放尺寸 --------------------- data_dst util faceset resize.bat"
attrib -h "3.4)--- DST-aligned 排序 -------------------------- data_dst sort.bat"
attrib -h "3.5)--- DST-aligned 打包 -------------------------- data_dst util faceset pack.bat"
attrib -h "3.5)--- DST-aligned 解包 -------------------------- data_dst util faceset unpack.bat"
attrib -h "3.6)--- DST-aligned 文件名恢复 ------------------- data_dst util recover original filename.bat"