@echo off
chcp 65001 > nul
attrib +h "4)———————————[ 遮罩 处理 —— XSeg Tools ]———————————————————————————————.bat"
attrib -h "4)++++++++++++++++[ 遮罩 处理 —— XSeg Tools ]+++++++++++++++++++++++++++++++++++++++++++++.bat"
attrib -h "4.1)--- DST-aligned 画遮罩 ----------------------- data_dst mask - edit.bat"
attrib -h "4.1)--- SRC-aligned 画遮罩 ----------------------- data_src mask - edit.bat"
attrib -h "4.2)--- SRC+DST 训练遮罩模型 -------------------- train Xseg.bat"
attrib -h "4.3)--- DST-aligned 使用内置遮罩 ---------------- data_dst whole_face mask - apply.bat"
attrib -h "4.3)--- DST-aligned 应用自定遮罩 ---------------- data_dst trained mask - apply.bat"
attrib -h "4.3)--- SRC-aligned 使用内置遮罩 ---------------- data_src whole_face mask - apply.bat"
attrib -h "4.3)--- SRC-aligned 应用自定遮罩 ---------------- data_src trained mask - apply.bat"
attrib -h "4.4)--- DST-aligned 移除手绘 --------------------- data_dst mask - remove.bat"
attrib -h "4.4)--- DST-aligned 移除遮罩 --------------------- data_dst trained mask - remove.bat"
attrib -h "4.4)--- SRC-aligned 移除手绘 --------------------- data_src mask - remove.bat"
attrib -h "4.4)--- SRC-aligned 移除遮罩 --------------------- data_src trained mask - remove.bat"
attrib -h "4.5)--- DST-aligned 遮罩提取 --------------------- data_dst mask - fetch.bat"
attrib -h "4.5)--- SRC-aligned 遮罩提取 --------------------- data_src mask - fetch.bat"