# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\DeepFaceLab\_internal\facesets\UI\FaceGrid_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        Dialog.setMinimumSize(QtCore.QSize(800, 600))
        Dialog.setMaximumSize(QtCore.QSize(800, 600))
        Dialog.setStyleSheet("background-color:#444444")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_main = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_main.sizePolicy().hasHeightForWidth())
        self.groupBox_main.setSizePolicy(sizePolicy)
        self.groupBox_main.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_main.setStyleSheet("border:1px solid rgb(130, 130, 130);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"font-size:12px;\n"
"font-weight:300;\n"
"color:rgb(255, 255, 255)")
        self.groupBox_main.setObjectName("groupBox_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_main)
        self.verticalLayout.setContentsMargins(-1, 12, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView_main = QtWidgets.QGraphicsView(self.groupBox_main)
        self.graphicsView_main.setStyleSheet("background-color:#222222")
        self.graphicsView_main.setObjectName("graphicsView_main")
        self.verticalLayout.addWidget(self.graphicsView_main)
        self.pushButton_openMain = QtWidgets.QPushButton(self.groupBox_main)
        self.pushButton_openMain.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_openMain.setAutoFillBackground(False)
        self.pushButton_openMain.setStyleSheet("QPushButton {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    color: #BDC8E2;\n"
"    font-weight: bold;\n"
"\n"
"    text-align: center;\n"
"    padding-left: 0px;\n"
"    padding-top: 0px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 2px;\n"
"    background-color: #2E3648;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: red;\n"
"    border-color: green;\n"
"    background-color: aqua;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: green;\n"
"    border-color: blueviolet;\n"
"    background-color: black;\n"
"}\n"
"QPushButton:disabled{\n"
"    color: blue;\n"
"    border-color: brown;\n"
"    background-color: aqua;\n"
"}")
        self.pushButton_openMain.setFlat(False)
        self.pushButton_openMain.setObjectName("pushButton_openMain")
        self.verticalLayout.addWidget(self.pushButton_openMain)
        self.verticalLayout_4.addWidget(self.groupBox_main)
        self.groupBox_Second = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Second.sizePolicy().hasHeightForWidth())
        self.groupBox_Second.setSizePolicy(sizePolicy)
        self.groupBox_Second.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_Second.setStyleSheet("border:1px solid rgb(130, 130, 130);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"font-size:12px;\n"
"font-weight:300;\n"
"color:rgb(255, 255, 255)")
        self.groupBox_Second.setObjectName("groupBox_Second")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_Second)
        self.verticalLayout_2.setContentsMargins(-1, 12, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphicsView_Second = QtWidgets.QGraphicsView(self.groupBox_Second)
        self.graphicsView_Second.setStyleSheet("background-color:#222222")
        self.graphicsView_Second.setObjectName("graphicsView_Second")
        self.verticalLayout_2.addWidget(self.graphicsView_Second)
        self.pushButton_openSecond = QtWidgets.QPushButton(self.groupBox_Second)
        self.pushButton_openSecond.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_openSecond.setStyleSheet("QPushButton {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    color: #BDC8E2;\n"
"    font-weight: bold;\n"
"\n"
"    text-align: center;\n"
"    padding-left: 0px;\n"
"    padding-top: 0px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 2px;\n"
"    background-color: #2E3648;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: red;\n"
"    border-color: green;\n"
"    background-color: aqua;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: green;\n"
"    border-color: blueviolet;\n"
"    background-color: black;\n"
"}\n"
"QPushButton:disabled{\n"
"    color: blue;\n"
"    border-color: brown;\n"
"    background-color: aqua;\n"
"}")
        self.pushButton_openSecond.setObjectName("pushButton_openSecond")
        self.verticalLayout_2.addWidget(self.pushButton_openSecond)
        self.verticalLayout_4.addWidget(self.groupBox_Second)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_title = QtWidgets.QLabel(Dialog)
        self.label_title.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_5.addWidget(self.label_title)
        self.checkBox_rightClick = QtWidgets.QCheckBox(Dialog)
        self.checkBox_rightClick.setStyleSheet("font-family: \"Microsoft YaHei\";\n"
"    color: #BDC8E2;\n"
"    font-weight: bold;\n"
"\n"
"    text-align: center;\n"
"    padding-left: 0px;\n"
"    padding-top: 0px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 2px;\n"
"    background-color: #2E3648;")
        self.checkBox_rightClick.setObjectName("checkBox_rightClick")
        self.horizontalLayout_5.addWidget(self.checkBox_rightClick)
        self.horizontalLayout_5.setStretch(0, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5.addWidget(self.frame)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.verticalLayout_5.setStretch(0, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_6.setStretch(1, 1)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setStyleSheet("color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.progressBar_analyzeMain = QtWidgets.QProgressBar(Dialog)
        self.progressBar_analyzeMain.setStyleSheet("QProgressBar {\n"
"    /* 外边框 */\n"
"    border:1px solid rgb(130, 130, 130);  \n"
"    /* 倒角 */\n"
"    border-radius:5px; \n"
"    /* 字体对齐方式 */\n"
"    text-align:center;\n"
"color:rgb(255, 255, 255);\n"
"}\n"
" \n"
"/* 进度条 */\n"
"QProgressBar::chunk {\n"
"    /* 颜色 */\n"
"    background-color:#05B8CC;\n"
"    /* 步进距离 */\n"
"    width:5px; \n"
"    /* 进度条中间空白区域宽度 */\n"
"    margin:1px;\n"
"}")
        self.progressBar_analyzeMain.setProperty("value", 0)
        self.progressBar_analyzeMain.setObjectName("progressBar_analyzeMain")
        self.horizontalLayout_2.addWidget(self.progressBar_analyzeMain)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.progressBar_analyzeSecond = QtWidgets.QProgressBar(Dialog)
        self.progressBar_analyzeSecond.setStyleSheet("QProgressBar {\n"
"    /* 外边框 */\n"
"    border:1px solid rgb(130, 130, 130);  \n"
"    /* 倒角 */\n"
"    border-radius:5px; \n"
"    /* 字体对齐方式 */\n"
"    text-align:center;\n"
"color:rgb(255, 255, 255);\n"
"}\n"
" \n"
"/* 进度条 */\n"
"QProgressBar::chunk {\n"
"    /* 颜色 */\n"
"    background-color:#05B8CC;\n"
"    /* 步进距离 */\n"
"    width:5px; \n"
"    /* 进度条中间空白区域宽度 */\n"
"    margin:1px;\n"
"}")
        self.progressBar_analyzeSecond.setProperty("value", 0)
        self.progressBar_analyzeSecond.setObjectName("progressBar_analyzeSecond")
        self.horizontalLayout_3.addWidget(self.progressBar_analyzeSecond)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.progressBar_repak = QtWidgets.QProgressBar(Dialog)
        self.progressBar_repak.setStyleSheet("QProgressBar {\n"
"    /* 外边框 */\n"
"    border:1px solid rgb(130, 130, 130);  \n"
"    /* 倒角 */\n"
"    border-radius:5px; \n"
"    /* 字体对齐方式 */\n"
"    text-align:center;\n"
"color:rgb(255, 255, 255);\n"
"}\n"
" \n"
"/* 进度条 */\n"
"QProgressBar::chunk {\n"
"    /* 颜色 */\n"
"    background-color:#05B8CC;\n"
"    /* 步进距离 */\n"
"    width:5px; \n"
"    /* 进度条中间空白区域宽度 */\n"
"    margin:1px;\n"
"}")
        self.progressBar_repak.setProperty("value", 0)
        self.progressBar_repak.setObjectName("progressBar_repak")
        self.horizontalLayout_4.addWidget(self.progressBar_repak)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.pushButton_createPak = QtWidgets.QPushButton(Dialog)
        self.pushButton_createPak.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_createPak.setStyleSheet("QPushButton {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    color: #BDC8E2;\n"
"    font-weight: bold;\n"
"\n"
"    text-align: center;\n"
"    padding-left: 0px;\n"
"    padding-top: 0px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 2px;\n"
"    background-color: #2E3648;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: red;\n"
"    border-color: green;\n"
"    background-color: aqua;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: green;\n"
"    border-color: blueviolet;\n"
"    background-color: black;\n"
"}\n"
"QPushButton:disabled{\n"
"    color: blue;\n"
"    border-color: brown;\n"
"    background-color: aqua;\n"
"}")
        self.pushButton_createPak.setObjectName("pushButton_createPak")
        self.verticalLayout_7.addWidget(self.pushButton_createPak)
        self.verticalLayout_7.setStretch(0, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "项目选择"))
        self.groupBox_main.setTitle(_translate("Dialog", "主素材Aligned头像"))
        self.pushButton_openMain.setText(_translate("Dialog", "打开文件夹"))
        self.groupBox_Second.setTitle(_translate("Dialog", "扩充素材Aligned头像"))
        self.pushButton_openSecond.setText(_translate("Dialog", "打开文件夹"))
        self.label_title.setText(_translate("Dialog", "1.4多功能版"))
        self.checkBox_rightClick.setText(_translate("Dialog", "激活右键预览"))
        self.label_5.setText(_translate("Dialog", "↑\n"
"丨\n"
"丨\n"
"丨\n"
"仰\n"
"俯\n"
"丨\n"
"丨\n"
"丨\n"
"↓"))
        self.label_6.setText(_translate("Dialog", "←----------右左----------→"))
        self.label.setText(_translate("Dialog", "主素材分析"))
        self.label_2.setText(_translate("Dialog", "扩充素材分析"))
        self.label_3.setText(_translate("Dialog", "生成pak"))
        self.pushButton_createPak.setText(_translate("Dialog", "生成pak"))
